### ISSUE TITLE
PLEASE ADD SUPPORT FOR GC0329 AND GC0307 CMOS SENSORS

### ISSUE THREAD

**Issue by sburdka** [sumotoy/ArduCAM#5]
we are working with GC0329 Cmos sensors. Initially we are facing some problem to deal with this sensors can you please add the support for it.
Datasheet: 
1. http://www.gcoreinc.com/upload/file/1376529297.pdf

**Comment by supprot** [comment]
We don't have GC0329 sensor at hand, so it might be a problem to add support for this sensor for the moment.
I think you can use our ArduCAM shield V2 with LCD screen and tune the sensor  yourself.

**Comment by suyog44** [comment]
I am also trying the same. When i am trying to initilaise the module, first i am write 8 byte sensor address  and try to pull device response , but instead of getting hex value i am getting all zeros. Can you give some rough idea how to do it.

The code is like this
 void Sensor_Init(void)
{
 u8 rtn;
 I2C_WriteSensorRegister(0xfc , 0x16);
 rtn = I2C_ReadSensorRegister(0x00);
 I2C_WriteSensorRegister(0xfe , 0x80);
 I2C_WriteSensorRegister(0xfe , 0x00);
 I2C_WriteSensorRegister(0xfc , 0x16);
 I2C_WriteSensorRegister(0xf1 , 0x01);
 I2C_WriteSensorRegister(0xf0 , 0x07);
 I2C_WriteSensorRegister(0xfa , 0x00);
 I2C_WriteSensorRegister(0x24 , 0x3f);
 I2C_WriteSensorRegister(0x46 , 0x02);
 I2C_WriteSensorRegister(0x09 , 0x00);
 I2C_WriteSensorRegister(0x0a , 0x04);
 I2C_WriteSensorRegister(0x0b , 0x00);
 I2C_WriteSensorRegister(0x0c , 0x00);
 I2C_WriteSensorRegister(0x0d , 0x01);
 I2C_WriteSensorRegister(0x0e , 0xe8);
 I2C_WriteSensorRegister(0x0f , 0x02);
 I2C_WriteSensorRegister(0x10 , 0x88);
 I2C_WriteSensorRegister(0x17 , 0x14);
 I2C_WriteSensorRegister(0x19 , 0x05);
 I2C_WriteSensorRegister(0x1F , 0xC0);
 I2C_WriteSensorRegister(0x1E , 0x15);
 I2C_WriteSensorRegister(0x20 , 0x00);
 I2C_WriteSensorRegister(0x21 , 0x48);
 I2C_WriteSensorRegister(0x22 , 0xDA);
 I2C_WriteSensorRegister(0x23 , 0x41);
 I2C_WriteSensorRegister(0x24 , 0x16);
 I2C_WriteSensorRegister(0x33 , 0x20);
 I2C_WriteSensorRegister(0x34 , 0x20);
 I2C_WriteSensorRegister(0x35 , 0xFF);
 I2C_WriteSensorRegister(0x36 , 0xFF);
 I2C_WriteSensorRegister(0x41 , 0x00);
 I2C_WriteSensorRegister(0x42 , 0xFE);
 I2C_WriteSensorRegister(0x4F , 0x00);
 I2C_WriteSensorRegister(0x70 , 0x40);
 I2C_WriteSensorRegister(0x76 , 0x8A);
 I2C_WriteSensorRegister(0xB0 , 0x00);
 I2C_WriteSensorRegister(0xBC , 0x00);
 I2C_WriteSensorRegister(0xBD , 0x00);
 I2C_WriteSensorRegister(0xBE , 0x00);
I2C_WriteSensorRegister(0x4D , 0x03);
 I2C_WriteSensorRegister(0xfe , 0x00);
 I2C_WriteSensorRegister(0x4b , 0xCA);
 I2C_WriteSensorRegister(0x50 , 0x01);
 I2C_WriteSensorRegister(0x51 , 0x00);
 I2C_WriteSensorRegister(0x52 , 0x00);
 I2C_WriteSensorRegister(0x53 , 0x00);
 I2C_WriteSensorRegister(0x54 , 0x00);
 I2C_WriteSensorRegister(0x55 , 0x00);
 I2C_WriteSensorRegister(0x56 , 0xf0);
 I2C_WriteSensorRegister(0x57 , 0x01);
 I2C_WriteSensorRegister(0x58 , 0x40);
 I2C_WriteSensorRegister(0x59 , 0x22);
 I2C_WriteSensorRegister(0x5a , 0x03);
 I2C_WriteSensorRegister(0x5b , 0x00);
 I2C_WriteSensorRegister(0x5c , 0x00);
 I2C_WriteSensorRegister(0x5d , 0x00);
 I2C_WriteSensorRegister(0x5e , 0x00);
 I2C_WriteSensorRegister(0x5f , 0x00);
 I2C_WriteSensorRegister(0x60 , 0x00);
 I2C_WriteSensorRegister(0x61 , 0x00);
 I2C_WriteSensorRegister(0x62 , 0x00);
 I2C_WriteSensorRegister(0x03 , EEPROM[7]);
 I2C_WriteSensorRegister(0x04 , EEPROM[8]);
 I2C_WriteSensorRegister(0x44 , 0x02);
 I2C_WriteSensorRegister(0x11 , 0x2A);
 I2C_WriteSensorRegister(0x40 , 0xBf);
 I2C_WriteSensorRegister(0x41 , 0x02);
 I2C_WriteSensorRegister(0x70 , 0x75);
 I2C_WriteSensorRegister(0x7A , 0xFF);
 I2C_WriteSensorRegister(0x7B , 0x70);
 I2C_WriteSensorRegister(0x7C , 0xFF);
 I2C_WriteSensorRegister(0xD3 , 0x80);
 I2C_WriteSensorRegister(0x63 , 0x00);
 I2C_WriteSensorRegister(0x64 , 0x0B);
 I2C_WriteSensorRegister(0x65 , 0x19);
 I2C_WriteSensorRegister(0x66 , 0x2B);
 I2C_WriteSensorRegister(0x67 , 0x37);
 I2C_WriteSensorRegister(0x68 , 0x48);
 I2C_WriteSensorRegister(0x69 , 0x51);
 I2C_WriteSensorRegister(0x6A , 0x5E);
 I2C_WriteSensorRegister(0x6B , 0x97);
 I2C_WriteSensorRegister(0x6C , 0xB2);
 I2C_WriteSensorRegister(0x6D , 0xC9);
 I2C_WriteSensorRegister(0x6E , 0xDF);
 I2C_WriteSensorRegister(0x6F , 0xFF); 
}
